### PR TITLE
[Issue #23] Fix RFC5424 formatter to add STRUCTURED-DATA field

### PR DESCRIPTION
**Pull request by bluttringer**
Pull request related to Issue #23

### CODE REVIEW

**Comment by sirsean** [comment]
Thank you for this!

My reading of the RFC is the same as yours, that in order to correctly adhere to the spec, we're going to want to add that `-` for empty structured data. (And ideally add the ability to actually have structured data at some point, but presumably we'd need to add something to the interface to support that.)

The code looks fine to me, but I want to do a little bit of research to make sure this is a safe change. Unfortunately I've run into cases where syslog endpoints that we send to don't correctly parse a message if it's compliant (usually in the case of requiring an amalgamation of 5424 and 3164), and I _really_ want to avoid doing something that breaks existing code in a way that is "more correct in an unexpected way".

I'll dig. It's possible that we'll want to include multiple versions of `RFC5424Formatter` and the one that supports structured data should be either the default or not the default? I'm not sure how I feel about that suggestion.

**Comment by bluttringer** [comment]
Hi,

I get that certain syslog endpoint that claim to be compliant are actually not! :) 
But ok, I understand you don't want to break anything already working.

Concerning your proposal of creating a new Formatter, I think this is the correct way to do that. We could create a RFC5224StructuredDataFormatter or something like that. Is there a way we can parameterize the formatters? If there is, we can add a parameter to add structured data, which will be 'false' by default. 

I think the current way of formatting the RFC5424 has to stay the default one.

**Comment by sirsean** [comment]
I can't think of a (good) way to add support for putting structured data into the messages that doesn't look something like this:

```go
type StructuredDataPair struct {
    Name string
    Value string
}

type Formatter func(p Priority, hostname, tag, content string, structuredData ...StructuredDataPair) string
```

It'd require updating the signature of all the existing formatters, but not their functionality or their callers (thanks to the vararg).

The tricky/annoying bit would then be updating `writer.go` to take a  `...StructuredDataPair` in a bunch of places so it could pass it along to eventually get down to the formatter.

**Comment by bluttringer** [comment]
I think Structured data only applies to RFC5424, maybe it wouldn't be very clear to add the parameter to the top object Formatter.

**Comment by sirsean** [comment]
It does only apply to 5424, but I would really prefer to only have one `Formatter` interface that all the formatters can implement.

Over in the writer, we're really going to not want to care which formatter is active, we just want to pass data to it and have it formatted.

But that's a good point, and adding structured data fields to the other formatter functions even though they're supposed to ignore them kind of sucks. This _may_ be an argument for switching to something like:

```go
type FormatterArgs struct {
    Priority Priority
    Hostname string
    Tag string
    Content string
    StructuredData []StructuredDataPair
}

type Formatter func(fa FormatterArgs) string
```

Which would be clumsier to implement and call, but avoids having unnecessary parameters being explicitly defined in functions that don't want them.

**Comment by sirsean** [comment]
By the way, I'm coming around to an inclination to merge this as-is.

RFC 5424 support is new in srslog (ie, is not a holdover from the original syslog package). And correctly adhering to the spec is something that we should've had from the beginning. I absolutely don't want a situation where we have ongoing support for "broken" 5424 and "correct" 5424. And if we're going to have to change the `Formatter` interface to support structured data anyway, having two versions of 5424 doesn't make sense.

**Comment by bluttringer** [comment]
Yep, I totally agree! :+1:

**Pull request merged**
