### PR TITLE
Suppress vet warnings about mutex copy

### PR DESCRIPTION
**Pull request by LK4D4**
Also, it is a recommendation from Google Code Review Guide.

### CODE REVIEW

**Comment by reaperhulk** [comment]
This PR has a conflict related to the latest merge, would you mind rebasing/merging master for us? Thanks! (The test failure that was present should be resolved by latest master as well)

**Comment by sirsean** [comment]
This makes me think we should add `go vet` to CI.

(Also we _almost_ got the "dialer tests need to be more robust" in in time for this, haha.)

**Comment by LK4D4** [comment]
@reaperhulk rebased

**Comment by sirsean** [comment]
:+1: Thanks for this.

**Pull request merged**
